// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPZN9a74dhf0R2v-C9cRmT8ER1aDxxhR0',
    appId: '1:581544879147:web:e897f86f285dc854a2b66e',
    messagingSenderId: '581544879147',
    projectId: 'tech-a-thon-2ba54',
    authDomain: 'tech-a-thon-2ba54.firebaseapp.com',
    storageBucket: 'tech-a-thon-2ba54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqzHsM_iIyq7TngMijAGfHAwx5h4_N60',
    appId: '1:581544879147:android:cc737161cc18fccfa2b66e',
    messagingSenderId: '581544879147',
    projectId: 'tech-a-thon-2ba54',
    storageBucket: 'tech-a-thon-2ba54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxref5sfkKd6DCintf_5NQQ7hIUzdBCJw',
    appId: '1:581544879147:ios:ae19ed164ef007d4a2b66e',
    messagingSenderId: '581544879147',
    projectId: 'tech-a-thon-2ba54',
    storageBucket: 'tech-a-thon-2ba54.appspot.com',
    iosBundleId: 'com.example.techathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxref5sfkKd6DCintf_5NQQ7hIUzdBCJw',
    appId: '1:581544879147:ios:6198ba1a04c76e4fa2b66e',
    messagingSenderId: '581544879147',
    projectId: 'tech-a-thon-2ba54',
    storageBucket: 'tech-a-thon-2ba54.appspot.com',
    iosBundleId: 'com.example.techathon.RunnerTests',
  );
}
